"""Phase 33.1 — agent-server bundle builder.

Produces a self-contained Python source string that:

  1. Embeds ``WorkspaceStat`` (the only `app.tools.workspace` symbol
     the server uses).
  2. Embeds ``sha256_file`` (the only `app.tools.hash_ops` symbol).
  3. Embeds the full ``protocol.py`` content.
  4. Embeds the full ``server.py`` content.
  5. Reads ``AGENT_SERVER_PORT`` / ``AGENT_SERVER_TOKEN`` /
     ``AGENT_SERVER_WORKSPACE`` from env (or generates defaults).
  6. Calls ``_main()`` which binds the server + prints
     ``AGENT_SERVER_PORT/TOKEN/WORKSPACE`` lines to stdout, then
     serves until SIGTERM / SIGINT.

The bundle is meant to be fed to ``python3 -c "<bundle>"`` over
``docker exec -i`` or ``ssh``. No files written; no module structure.

§10.7: this is application-layer plumbing — no kernel imports added.
The bundled source comes from `app.tools.agent_server.protocol` +
`app.tools.agent_server.server` which already live in the tools
layer; this module assembles them into a `-c`-friendly script string.
"""

from __future__ import annotations

import hashlib
import re
from functools import lru_cache
from pathlib import Path

# Import statements we strip from the embedded source modules — the
# referenced symbols are inlined directly above in the bundle, so
# importing them via the in-package path would fail at runtime.
_STRIP_IMPORT_PREFIXES = (
    "from app.tools.agent_server.protocol",
    "from app.tools.hash_ops",
)


def _strip_app_imports(source: str) -> str:
    """Drop ``from app.*`` import statements (single- or multi-line)
    that reference symbols we've already inlined.

    Handles three syntactic shapes:

      1. ``from app.x import a``                 — single line
      2. ``from app.x import a, b``              — single line, multi-symbol
      3. ``from app.x import (\\n    a,\\n    b,\\n)`` — multi-line block
    """
    out_lines: list[str] = []
    lines = source.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        # Is this the start of an import we want to drop?
        matches = any(stripped.startswith(prefix) for prefix in _STRIP_IMPORT_PREFIXES)
        if matches:
            # If the line opens a paren block, consume forward until
            # the matching close-paren line. Otherwise it's a single
            # line — skip it.
            if "(" in stripped and ")" not in stripped:
                i += 1
                while i < len(lines) and ")" not in lines[i]:
                    i += 1
                # Skip the closing-paren line too.
                if i < len(lines):
                    i += 1
            else:
                i += 1
            continue
        out_lines.append(line)
        i += 1
    return "\n".join(out_lines)


_BUNDLE_HEADER = '''"""Bundled LocalFlow agent-server — generated by app.tools.agent_server.bundle.

Do NOT edit by hand. Regenerate via build_bundle().
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import secrets
import shutil
import signal
import socket
import sys
import threading
from collections.abc import Callable
from dataclasses import dataclass, field
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Protocol

try:
    from pydantic import BaseModel, ConfigDict, Field, ValidationError
except ImportError as exc:  # pragma: no cover - bundle bootstrap diagnostic
    sys.stderr.write(
        "agent-server bundle requires pydantic; install with `pip install pydantic`\\n"
    )
    raise SystemExit(2) from exc


# ── inlined WorkspaceStat (from app.tools.workspace) ──────────────────


@dataclass(frozen=True)
class WorkspaceStat:
    rel_path: str
    size_bytes: int
    is_file: bool
    is_dir: bool


# ── inlined sha256_file (from app.tools.hash_ops) ─────────────────────


_HASH_CHUNK = 64 * 1024


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        while True:
            buf = f.read(_HASH_CHUNK)
            if not buf:
                break
            h.update(buf)
    return h.hexdigest()


'''


_BUNDLE_FOOTER = """
# ── entrypoint ────────────────────────────────────────────────────────


def _main() -> None:
    workspace_root = Path(os.environ.get("AGENT_SERVER_WORKSPACE", "/workspace"))
    port = int(os.environ.get("AGENT_SERVER_PORT", "0"))
    host = os.environ.get("AGENT_SERVER_HOST", "127.0.0.1")
    token = os.environ.get("AGENT_SERVER_TOKEN") or secrets.token_hex(32)
    server = AgentServer(workspace_root=workspace_root, port=port, token=token, host=host)
    server.start()
    sys.stdout.write(f"AGENT_SERVER_PORT={server.port}\\n")
    sys.stdout.write(f"AGENT_SERVER_TOKEN={server.token}\\n")
    sys.stdout.write(f"AGENT_SERVER_WORKSPACE={server.workspace_root}\\n")
    sys.stdout.flush()

    stopping = threading.Event()

    def _handler(*_: Any) -> None:
        stopping.set()

    signal.signal(signal.SIGTERM, _handler)
    signal.signal(signal.SIGINT, _handler)
    try:
        stopping.wait()
    finally:
        server.stop()


if __name__ == "__main__":
    _main()
"""


def _strip_module_docstring(source: str) -> str:
    """Remove the leading module docstring so the bundle keeps a single
    top-level docstring (the bundle header's)."""
    # Match the very-first triple-quoted block at module top, possibly
    # preceded by `from __future__ import annotations`.
    pattern = re.compile(
        r'^\s*(?:from __future__ import annotations\s*\n+)?"""[\s\S]*?"""\s*\n',
    )
    return pattern.sub("", source, count=1)


def _strip_future_import(source: str) -> str:
    """Remove `from __future__ import annotations` (already emitted in
    the bundle header)."""
    return re.sub(r"^from __future__ import annotations\s*\n", "", source, count=1)


def _strip_main_block(source: str) -> str:
    """Remove the in-module ``_main()`` + ``if __name__ == "__main__":``
    block in server.py — the bundle ships its own ``_main()`` wired to
    the inlined modules (see ``_BUNDLE_FOOTER`` below).

    Server.py's main block is preceded by a section divider using
    Unicode box-drawing characters (── module-as-entrypoint ──).
    Match that anchor + drop everything from it to end of file.
    """
    # Anchor: the section comment line containing "module-as-entrypoint".
    # Any preceding/following whitespace is fine; we want to drop from
    # the first occurrence onward.
    return re.sub(
        r"\n[^\n]*module-as-entrypoint[^\n]*\n.*$",
        "",
        source,
        flags=re.DOTALL,
    )


def _strip_stdlib_imports(source: str) -> str:
    """Remove stdlib import statements that the bundle header already
    contains, plus the typing/pydantic ones."""
    lines = source.split("\n")
    keep = []
    skip_prefixes = (
        "import base64",
        "import hashlib",
        "import json",
        "import os",
        "import re",
        "import secrets",
        "import shutil",
        "import signal",
        "import socket",
        "import sys",
        "import threading",
        "import urllib",
        "from collections.abc import",
        "from dataclasses import",
        "from http import",
        "from http.server import",
        "from pathlib import",
        "from typing import",
        "from pydantic import",
    )
    for line in lines:
        stripped = line.lstrip()
        if any(stripped.startswith(prefix) for prefix in skip_prefixes):
            continue
        keep.append(line)
    return "\n".join(keep)


def _module_source(module_path: Path) -> str:
    """Read + light-clean a Python module file for embedding."""
    text = module_path.read_text(encoding="utf-8")
    text = _strip_module_docstring(text)
    text = _strip_future_import(text)
    text = _strip_app_imports(text)
    text = _strip_stdlib_imports(text)
    text = _strip_main_block(text)
    # Collapse multiple blank lines.
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + "\n"


@lru_cache(maxsize=1)
def build_bundle() -> str:
    """Return the standalone Python source string. Cached because
    the inputs are static at process lifetime."""
    pkg_dir = Path(__file__).parent
    protocol_src = _module_source(pkg_dir / "protocol.py")
    server_src = _module_source(pkg_dir / "server.py")
    return (
        _BUNDLE_HEADER
        + "# ── inlined protocol.py ─────────────────────────────────────────────\n\n"
        + protocol_src
        + "\n# ── inlined server.py ───────────────────────────────────────────────\n\n"
        + server_src
        + _BUNDLE_FOOTER
    )


def bundle_sha256() -> str:
    """Hex digest of the bundled source — useful for cache keys + test
    pinning."""
    return hashlib.sha256(build_bundle().encode("utf-8")).hexdigest()


__all__ = ["build_bundle", "bundle_sha256"]
