"""Example external skill — workspace_stats.

Hello-world plugin proving Phase 4.1 filesystem discovery works.
Generates a single ``workspace_stats.md`` summarizing the file count
by ``file_type`` category, plus total bytes.

This file's only requirement to be picked up by LocalFlow:
  * Live in a subdirectory of one of the discovery paths (see
    ``localflow skills`` for the list).
  * Be named ``skill.py``.
  * Define exactly one subclass of ``Skill``.

Everything else (planner.py, validator.py, reporter.py, skill.yaml) is
optional — they only help YOU stay organized.
"""

from __future__ import annotations

import uuid
from pathlib import Path

from app.schemas import ActionPlan, SkillManifest, TaskSpec, WorkspaceSnapshot, VerificationResult
from app.schemas.action import Action, ActionType, RiskLevel
from app.skills._base import Skill


class WorkspaceStatsSkill(Skill):
    """Tiny example skill: tabulate the workspace, write a stats report."""

    @property
    def manifest(self) -> SkillManifest:
        return SkillManifest(
            name="workspace_stats",
            description="Phase 4.1 example external skill — counts files by category.",
            version="0.1.0",
            capabilities=["scan_workspace", "render_markdown_report"],
            # Phase 4.2: a skill that called e.g. data_ops.read_tabular
            # would declare it here — the loader validates the name
            # resolves in the Tool Registry. This skill only iterates
            # snapshot.files (populated by the harness), so the list is
            # empty.
            required_tools=[],
            allowed_actions=["index"],
            requires_approval=["index"],
            supports_dry_run=True,
            supports_rollback=True,
            supports_verify=True,
        )

    def plan(self, task: TaskSpec, snapshot: WorkspaceSnapshot) -> ActionPlan:
        by_type: dict[str, int] = {}
        by_size: dict[str, int] = {}
        for f in snapshot.files:
            by_type[f.file_type] = by_type.get(f.file_type, 0) + 1
            by_size[f.file_type] = by_size.get(f.file_type, 0) + f.size_bytes

        lines: list[str] = [
            "# Workspace Stats",
            "",
            f"_Root: `{snapshot.root}`_",
            f"_Total files: {snapshot.total_files}; total size: {snapshot.total_size_bytes:,} bytes_",
            "",
            "| Category | Files | Size (bytes) |",
            "|---|---:|---:|",
        ]
        for cat in sorted(by_type):
            lines.append(f"| {cat} | {by_type[cat]} | {by_size[cat]:,} |")
        lines.append("")
        lines.append(
            "_Generated by the `workspace_stats` external skill loaded via "
            "Phase 4.1 filesystem discovery._"
        )
        content = "\n".join(lines)

        return ActionPlan(
            plan_id=f"plan-{uuid.uuid4().hex[:8]}",
            task_id=task.task_id,
            summary=f"Render workspace stats over {snapshot.total_files} file(s).",
            actions=[
                Action(
                    action_id="a-001",
                    action_type=ActionType.INDEX,
                    target_path="workspace_stats.md",
                    reason="Tabulate file counts and sizes by category.",
                    risk_level=RiskLevel.LOW,
                    reversible=True,
                    requires_approval=True,
                    metadata={
                        "content": content,
                        "overwrite_existing": True,
                        "provenance": {
                            "synthesis_kind": "workspace_stats",
                            "category_counts": dict(by_type),
                        },
                    },
                ),
            ],
            expected_outputs=["workspace_stats.md"],
            risk_summary="Low risk: single markdown write, fully reversible.",
        )

    def validate(self, plan: ActionPlan) -> None:
        if len(plan.actions) > 1:
            raise ValueError("workspace_stats only emits one action")
        for a in plan.actions:
            if a.action_type != ActionType.INDEX:
                raise ValueError(f"workspace_stats only emits index actions; got {a.action_type}")

    def report(
        self,
        *,
        task: TaskSpec,
        plan: ActionPlan,
        outcome,
        verification: VerificationResult,
    ) -> str:
        ok = "PASSED" if verification.passed else "FAILED"
        return (
            f"# workspace_stats final report — task `{task.task_id}`\n\n"
            f"- Workspace: `{task.workspace_root}`\n"
            f"- Verifier: **{ok}** — {verification.summary}\n"
            f"- Generated: `workspace_stats.md`\n"
        )
